name: test jsongraph-go

on:
  pull_request: []
  push:
    branches:
      - main

jobs:
  unit:
    strategy:
      matrix:
        os: [ubuntu-latest]
        go: ['^1.20.0']
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true
    - name: Set up Go
      uses: actions/setup-go@93397bea11091df50f3d7e59dc26a7711a8bcfbe
      with:
        go-version: ${{ matrix.go }}

    - name: Build and Basic Test
      run: |
        make
        make run
        # test -coverprofile=coveragetxt -race ./...